[build]
  publish = "." # or "dist" if you're building
  command = ""

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Allow direct access to assets (DO THIS!)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Prevent robots.txt from being redirected
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[prerender]
  enabled = true
