[build]
  publish = "dist" # change if your folder is named differently

[[edge_functions]]
  function = "hello"
  path = "/*"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[edge_functions.hello]
  generator = "@netlify/edge-functions"
  included_files = ["*.html", "*.js", "*.css", "img/**/*", "fonts/**/*"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[prerender]
  enabled = true
