[build]
  publish = "." # Change to "dist" if using a build step
  command = ""  # Add your build command if needed, or leave blank

# Edge Function routing
[[edge_functions]]
  function = "hello"
  path = "/*"

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Prerendering for SEO bots
[prerender]
  enabled = true

# Prevent robots.txt from being overridden by SPA redirect
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# SPA fallback redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
